### ISSUE TITLE
[Feature Request] Support for other mods in BelpnEx

### ISSUE THREAD

**Issue by MatadorProBr** [Herysia/CustomKeyBinds#3]
Well, when I saw this project I liked it, because I didn't like some keys that Among Us puts as default, and I was with CustomServersClient and GameSettingsUnlocker and started to give some bugs and from what I saw, CustomKeyBinds was bugging because there was other mods, so if you can make compatibility with other mods on BelpnEx I appreciate :D

**Comment by Herysia** [comment]
Hi @MatadorProBr, thx for your feedback,
Can you please explain further what mod is bugging and/or provide some logs pls ? Because i've been using it with many other mods without any issue.

Also, if you are thinking about mods that require new keybinds for their own actions (I'm thinking about Sheriff kill for example), I'm thinking about adding it in the future (probably next AU update if they haven't added keybinds support yet)

**Comment by MatadorProBr** [comment]
Well, here are the logs and thanks for responding quickly, I'm not using any sheriff mods or anything, just what I said above and even if I don't use sheriff mods I know that some friends will be happy with this update
[LogOutput.log](https://github.com/Herysia/CustomKeyBinds/files/5911162/LogOutput.log)

**Comment by Herysia** [comment]
You need Unity libs to get this mod to work, see releases, in `BepInEx\unhollowed\base`.
You can also download them from here if you prefer: https://github.com/HerpDerpinstine/MelonLoader/blob/master/BaseLibs/UnityDependencies/2019.4.9.zip

And copy Unity files to `BepInEx\unhollowed\base`.

**Comment by MatadorProBr** [comment]
Oh, sorry, I hadn't seen it, but when I put it on BelpnEx (which I downloaded from the BelpnEx website) it didn't work so I had to download the CustomKeyBinds version of the .zip, put it in the folder after I had to download the two plugins again and it looks like it worked now, I also updated my BelpnEx (to the latest version) and it seems that now everything is working as it should be, thank you!
